### ISSUE TITLE
Multiple protos in the same package importing each other

### ISSUE THREAD

**Issue by talkol** [tallstoat/pbparser#2]
The following fails:

**dependent.proto:**
```proto
syntax = "proto3";
package dep;

import "dependency.proto";

message Dependent {
    SamePackageDependencyMessage field = 1;
}
```

**dependency.proto:**
```proto
syntax = "proto3";
package dep;

message SamePackageDependencyMessage {
    string field = 1;
}
```

If the two files are defined in different packages, this works well. If they are defined under the same package, it fails with error "Datatype: 'SamePackageDependencyMessage' referenced in field: 'field' is not defined".

**Comment by talkol** [comment]
This also does not work:

**dependent.proto:**
```proto
syntax = "proto3";
package dep;

import "dependency.proto";

message Dependent {
    dep.SamePackageDependencyMessage field = 1;
}
```

**dependency.proto:**
```proto
syntax = "proto3";
package dep;

message SamePackageDependencyMessage {
    string field = 1;
}
```

**Comment by tallstoat** [comment]
Sorry about getting to this so late; unavoidable circumstances.

**Comment by tallstoat** [comment]
Above commit fixes this.
